USE master

CREATE DATABASE QLGV

USE QLGV

/*CAU 1*/
CREATE TABLE KHOA(
	MAKHOA VARCHAR(4),
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4),
	CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
)

CREATE TABLE MONHOC(
	MAMH VARCHAR(10),
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4),
	CONSTRAINT PK_MON_HOC PRIMARY KEY(MAMH)
)

CREATE TABLE DIEUKIEN(
	MAMH VARCHAR(10),
	MAMH_TRUOC VARCHAR(10),
	CONSTRAINT PK_DIEUKIEN PRIMARY KEY(MAMH, MAMH_TRUOC)
)

CREATE TABLE GIAOVIEN(
	MAGV CHAR(4),
	HOTEN VARCHAR(40),
	HOCVI CHAR(10),
	HOCHAM CHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4),
	CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MAGV)
)

CREATE TABLE LOP(
	MALOP CHAR(3),
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4),
	CONSTRAINT PK_LOP PRIMARY KEY(MALOP)
)

CREATE TABLE HOCVIEN(
	MAHV CHAR(5),
	HO VARCHAR(40),
	TEN VARCHAR(40),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3),
	CONSTRAINT PK_HOCVIEN PRIMARY KEY(MAHV)
)

CREATE TABLE GIANGDAY(
	MALOP CHAR(3),
	MAMH VARCHAR(10),
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	CONSTRAINT PK_GIANGDAY PRIMARY KEY (MALOP, MAMH)
)

CREATE TABLE KETQUATHI(
	MAHV CHAR(5),
	MAMH VARCHAR(10),
	LANTHI TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10),
	CONSTRAINT PK_KETQUATHI PRIMARY KEY (MAHV, MAMH, LANTHI)
)

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DK_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GD_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
	CONSTRAINT FK_GD_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	CONSTRAINT FK_GD_GV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KQT_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
	CONSTRAINT FK_KQT_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GV_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HV_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

ALTER TABLE MONHOC
ADD CONSTRAINT FK_MH_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)


/*CAU 2*/
ALTER TABLE HOCVIEN
ADD GHICHU VARCHAR(20),
	DIEMTB NUMERIC(4,2),
	XEPLOAI CHAR(10)

/*CAU 3*/
ALTER TABLE HOCVIEN
add CONSTRAINT HOCVIEN_GIOITINH CHECK(GIOITINH ='Nam' OR GIOITINH ='Nu')

ALTER TABLE GIAOVIEN
add CONSTRAINT GIAOVIEN_GIOITINH CHECK(gioitinh ='Nam' OR gioitinh='Nu')

/*CAU 4*/
ALTER TABLE KETQUATHI
add CONSTRAINT KETQUATHI_DIEM CHECK (diem >=0 AND diem <= 10)

/*CAU 5*/

/*CAU 6*/
ALTER TABLE KETQUATHI
add CONSTRAINT KETQUATHI_LANTHI CHECK (lanthi>=0 AND lanthi <=3)

/*CAU 7*/
ALTER TABLE GIANGDAY
add CONSTRAINT GIANGDAY_HOCKY CHECK(hocky>0 AND hocky <=3)

/*CAU 8*/
ALTER TABLE GIAOVIEN
add CONSTRAINT GIAOVIEN_HOCVI CHECK (hocvi = 'CN' OR hocvi = 'KS'
                                    OR hocvi = 'Ths' OR hocvi = 'TS'
                                    OR hocvi = 'PTS')
/*CAU 9*/
ALTER TABLE LOP


/*CAU 10*/

/*CAU 11*/
ALTER TABLE HOCVIEN
add CONSTRAINT HOCVIEN_

/*CAU 12*/
ALTER TABLE GIANGDAY
add CONSTRAINT GIANGDAY_TUNGAY_DENNGAY CHECK (tungay < denngay)

/*CAU 13*/

/*CAU 14*/
ALTER TABLE MONHOC
ADD CONSTRAINT MONHOC_TCLT_TCTH CHECK (abs(tclt -tcth) <153)

/*CAU 15*/

/*CAU 16*/
ALTER TABLE









