
CREATE DATABASE QLBH
USE QLBH

/*CAU 1*/
CREATE TABLE KHACHHANG(
	MAKH CHAR(4), CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH),
	HOTEN VARCHAR(40),
	DCHI VARCHAR(40),
	SODT VARCHAR(40),
	NGSINH SMALLDATETIME,
	NGDK SMALLDATETIME,
	DOANHSO MONEY,
)

CREATE TABLE NHANVIEN(
	MANV CHAR(4) CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV),
	HOTEN VARCHAR(40),
	SODT VARCHAR(40),
	NGVL SMALLDATETIME
)


CREATE TABLE SANPHAM(
	MASP CHAR(4) CONSTRAINT PK_SANPHAM PRIMARY KEY(MASP),
	TENSO VARCHAR(40),
	DVT VARCHAR(40),
	NUOCSX VARCHAR(40),
	GIA MONEY
)

CREATE TABLE HOADON(
	SOHD INT CONSTRAINT PK_SOHD PRIMARY KEY (SOHD),
	NGHD SMALLDATETIME,
	MAKH CHAR(4) CONSTRAINT FK_HD_KH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH) ,
	MANV CHAR(4) CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
	TRIGIA MONEY
)

CREATE TABLE CTHD(
	SOHD INT ,
	MASP CHAR(4) ,
	SL INT,
	CONSTRAINT PK_CTHD PRIMARY KEY (SOHD, MASP)
)

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY(SOHD) REFERENCES HOADON(SOHD)

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_SP FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)

/*CAU 2*/
ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20)

/*CAU 3*/
ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT

/*CAU 4*/
ALTER TABLE SANPHAM 
ALTER COLUMN GHICHU VARCHAR(100)

/*CAU 5*/
ALTER TABLE SANPHAM 
DROP COLUMN GHICHU

/*CAU 6*/



